### ISSUE TITLE
Làm web ZingMP3

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#1]

**Comment by phuongnguyenthi251199** [comment]
alo mọi người @hainguyenthe9  @hthuy99  bây giờ bắt đầu phân công nhiệm vụ cụ thể nhé

**Comment by hthuy99** [comment]
vâng

**Comment by hainguyenthe9** [comment]
aloo

**Comment by phuongnguyenthi251199** [comment]
@hainguyenthe9  xây dựng database trước , @hthuy99  thì tìm hiểu về giao diện

**Comment by phuongnguyenthi251199** [comment]
còn mình thì tìm hiểu về các chức năng của web..

**Comment by hthuy99** [comment]
ng dùng có comment dưới mỗi bài hát đc k v?

**Comment by hthuy99** [comment]
hay phải qua admin

**Comment by phuongnguyenthi251199** [comment]
Có nha, mình để chế độ cmt

**Comment by hainguyenthe9** [comment]
t nghĩ là có..  nhưng người dùng phải đăng nhập thì mới cmt được

**Comment by phuongnguyenthi251199** [comment]
Nếu muốn có thể cho admin duyệt cmt ấy có được hiển thị hay không

**Comment by phuongnguyenthi251199** [comment]
Nhiệm vụ mọi người như vậy nhá

**Comment by hthuy99** [comment]
oke

**Comment by hainguyenthe9** [comment]
oke..mn triển khai luôn đi nhé. có vấn đề gì thì post lên để cùng thảo luận
