### ISSUE TITLE
tạo album theo chủ đề và tải nhạc

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#10]

**Comment by phuongnguyenthi251199** [comment]
ablum thì sao

**Comment by phuongnguyenthi251199** [comment]
mọi người tìm hiểu cái này chưa

**Comment by hainguyenthe9** [comment]
phần tải nhạc thì mình làm ở issues người dùng download rồi thì thôi

**Comment by phuongnguyenthi251199** [comment]
mà có kiểu issues nào ko , mn gợi ý đi

**Comment by hainguyenthe9** [comment]
t nghĩ cũng giống phần tải nhạc lên thôi

**Comment by hainguyenthe9** [comment]
bây giờ người dùng click vào mục album và chọn chủ đề thì sẽ xổ ra các bài hát mà mình xếp theo chủ đề đấy

**Comment by hainguyenthe9** [comment]
https://www.youtube.com/watch?v=lcqr4XIiejk

**Comment by hainguyenthe9** [comment]
https://www.youtube.com/watch?v=sLDUSp-tvDA

**Comment by hainguyenthe9** [comment]
https://www.wpbeginner.com/plugins/9-best-audio-player-plugins-for-wordpress/

**Comment by hainguyenthe9** [comment]
ok không?
