### ISSUE TITLE
Tạo mục profile về ca sĩ nổi tiếng

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#11]

**Comment by phuongnguyenthi251199** [comment]
mục profile đơn giản là như kiểu thêm bài viết thôi nhỉ

**Comment by phuongnguyenthi251199** [comment]
thêm ảnh, sự nghiệp bài hát nổi bật...

**Comment by hainguyenthe9** [comment]
ừ, người dùng tìm kiếm bằng tên ca sĩ, thì ra tên các bài hát với 1 bài viết thông tin về ca sĩ đó thôi

**Comment by hainguyenthe9** [comment]
t nghĩ thế là đủ, k cần màu mè làm gì

**Comment by hainguyenthe9** [comment]
cái phần tìm tên ca sĩ hình như bọn mình có làm ở cái issues 3 rồi

**Comment by phuongnguyenthi251199** [comment]
mục này hôm trước giao ai làm đó nhỉ

**Comment by phuongnguyenthi251199** [comment]
xong chưa update tình hình đi

**Comment by hthuy99** [comment]
t làm xong r nhé

**Comment by hthuy99** [comment]
![screenshot-webdemo lionsoftwaresolutions com-2020 01 10-22_42_55](https://user-images.githubusercontent.com/56228860/72165806-bd5c3a00-33fa-11ea-82a7-87b5383e5c4c.png)
đây nhé

**Comment by hainguyenthe9** [comment]
![image](https://user-images.githubusercontent.com/51194378/72165789-b503ff00-33fa-11ea-9265-f7a4eede6cfe.png)
khá ok r

**Comment by hthuy99** [comment]
màu mè tí có ổn k :))

**Comment by phuongnguyenthi251199** [comment]
oke cậu ơi

**Comment by hthuy99** [comment]
oke sang issues khác nhé

**Comment by hainguyenthe9** [comment]
màu mè gì, tết nhất màu đỏ cho nó có tý không khí ^^

**Comment by hainguyenthe9** [comment]
sang issues khác thôi
