### ISSUE TITLE
Tạo danh sách các MV 

### ISSUE THREAD

**Issue by hainguyenthe9** [phuongnguyenthi251199/SE03-Group-08#12]
alo, ban đầu bọn mình làm thiếu cái issues này

**Comment by hainguyenthe9** [comment]
ở đây bọn mình cập nhất các MV hot cho người dùng, người dùng có thể nghe hoặc tải trực tiếp luôn

**Comment by hthuy99** [comment]
c làm r à :))

**Comment by hthuy99** [comment]
up luôn nhé cho Phương up code

**Comment by hthuy99** [comment]
cái này hình như nhúng từ youtube sang được đúng k?

**Comment by hainguyenthe9** [comment]
ừ đúng rồi, nhúng từ youtube sang

**Comment by hainguyenthe9** [comment]
![image](https://user-images.githubusercontent.com/51194378/72168337-8f2d2900-33ff-11ea-8253-937b2fcadd6a.png)

**Comment by hainguyenthe9** [comment]
ổn chưa bạn

**Comment by hthuy99** [comment]
oke b ơi.

**Comment by hthuy99** [comment]
mk vào nghe luôn cho nóng

**Comment by hainguyenthe9** [comment]
ok luôn bạn...

**Comment by hainguyenthe9** [comment]
vậy phần này coi như xong nhỉ
