### ISSUE TITLE
Xây dựng giao diện web ZingMP3

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#2]

**Comment by phuongnguyenthi251199** [comment]
@hainguyenthe9 @hthuy99 đầu tiên mình phải xây dựng trang chủ thật bắt mắt, vì là web âm nhạc nên cần show ra nhiều ảnh ca sĩ, ảnh banner, ảnh quảng cáo bài hát

**Comment by hainguyenthe9** [comment]
đúng rồi, sau đó sẽ phải xây dựng các module chức năng sao cho đáp ứng đầy đủ, tốt nhất nhu cầu của người dùng khi vào trang web của mình để nghe nhạc

**Comment by phuongnguyenthi251199** [comment]
các chức năng thì tất nhiên là có, mình sẽ liệt kê sau, nhg mà bây giờ nghĩ xem mình thêm những phần nào vào mục trang chủ, có thanh tìm kiếm, menu rồi, banner rồi, mn nghĩ thêm được gì không, như album chẳng hạn

**Comment by hthuy99** [comment]
dưới phần header t nghĩ sẽ là đề xuất các bài hát  mới ra hoặc các bài đang hot

**Comment by hthuy99** [comment]
sau đó sẽ là các album về các chủ để & thể loại nhạc ý

**Comment by phuongnguyenthi251199** [comment]
oke, ý kiến của Thúy hay đấy

**Comment by hainguyenthe9** [comment]
ngoài ra mình nghĩ nên có thêm bảng xếp hạng bài hát theo thể loại nhạc nữa

**Comment by hthuy99** [comment]
oke. Ae tìm hiểu plugin nào dùng để tạo album nhỉ

**Comment by phuongnguyenthi251199** [comment]
Thúy lên mạng tìm đi

**Comment by phuongnguyenthi251199** [comment]
cả Hải nữa

**Comment by hthuy99** [comment]
oke đang tìm hiểu

**Comment by hainguyenthe9** [comment]
mình nghĩ trước tiên mọi người nên định hình đưuọc giao diện sẽ có những gì đã, sau đó sẽ tập chung tìm plugin sauu

**Comment by hthuy99** [comment]
![screenshot-webdemo lionsoftwaresolutions com-2019 11 04-21_53_05](https://user-images.githubusercontent.com/56228860/68130469-fc2ec900-ff4d-11e9-8264-a0a7f2945031.png)

**Comment by phuongnguyenthi251199** [comment]
oke giao diện cũng ổn, kết thúc phần giao diện nha, bây giờ tập trung vào chức năng

**Comment by hainguyenthe9** [comment]
oke
