### ISSUE TITLE
Tạo chức năng tìm kiếm tên bài hát, tìm ca sĩ hoặc MV

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#3]

**Comment by hainguyenthe9** [comment]
alo alo, giờ làm chức năng này nhé

**Comment by phuongnguyenthi251199** [comment]
tạo cái thanh tìm kiếm nhể

**Comment by phuongnguyenthi251199** [comment]
giống như zingmp3 đó

**Comment by phuongnguyenthi251199** [comment]
giống như zingmp3 đó

**Comment by hainguyenthe9** [comment]
ừ, phải tạo 1 thanh tìm kiếm để người dùng search chứ

**Comment by hainguyenthe9** [comment]
tạo trên header cho người ta dễ nhìn

**Comment by phuongnguyenthi251199** [comment]
đấy đấy t cũng đang định bảo tạo ngay trên đầu ý

**Comment by phuongnguyenthi251199** [comment]
mà cậu ơi, tìm kiếm theo gì

**Comment by phuongnguyenthi251199** [comment]
theo tác giả, theo bài hát.. còn gì nữa ko nhỉ

**Comment by hainguyenthe9** [comment]
tìm kiếm theo tên bài hát, tên ca sĩ

**Comment by hainguyenthe9** [comment]
https://www.hostinger.vn/huong-dan/plugin-search-wordpress/

**Comment by phuongnguyenthi251199** [comment]
oke cậu

**Comment by hainguyenthe9** [comment]
mọi người tham khảo link trên đấy, có 1 số plugin search

**Comment by phuongnguyenthi251199** [comment]
cái này đơn giản, mình tạo frame rồi

**Comment by phuongnguyenthi251199** [comment]
h chỉ còn tạo một cái chức năng như kiểu lọc những từ người dùng nhập vào để nó hiện kết quả chính xác nhất

**Comment by hainguyenthe9** [comment]
ừ đấy, t cũng đang định bảo

**Comment by hainguyenthe9** [comment]
kiểu nhập tên bài hát hoặc ca sĩ thì sẽ xổ ra luôn kết quả mà k cần phải click search

**Comment by hainguyenthe9** [comment]
kiểu kết quả gợi ý ý

**Comment by hainguyenthe9** [comment]
gioosng zing, nhaccuatui hoặc chiasenhac đấy

**Comment by phuongnguyenthi251199** [comment]
cái đấy khó nhỉ

**Comment by hainguyenthe9** [comment]
ý tưởng là vậy
t thấy như vậy sẽ tiện, bọn mình sẽ thử làm xem.. nếu được thì okee
Còn không thì làm lọc bth, kiểu người dùng phải search rồi ra kết quả tìm kiếm ^.^

**Comment by hainguyenthe9** [comment]
à

**Comment by hainguyenthe9** [comment]
thế bây giờ chỉ tìm hiểu xây dựng chức năng lọc thôi nhỉ, còn frame build rồi nhỉ

**Comment by phuongnguyenthi251199** [comment]
oke frame xong rồi

**Comment by hainguyenthe9** [comment]
ok
thế giờ tìm hiểu cái kìa là nữa là oke

**Comment by hainguyenthe9** [comment]
![image](https://user-images.githubusercontent.com/51194378/72166403-bbdf4180-33fb-11ea-9b9a-d9fe389a4d38.png)
phần tìm kiếm ok chưa các chế

**Comment by hainguyenthe9** [comment]
gõ là ra gợi ý tên bài hát luôn r này

**Comment by hthuy99** [comment]
oke r đó
