### ISSUE TITLE
Xây dựng chức năng đăng nhập, đăng kí

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#4]
i

**Comment by hainguyenthe9** [comment]
t nghĩ nên bắt đầu xây dựng chức năng đăng nhập đăng ký trước

**Comment by hainguyenthe9** [comment]
alo alo

**Comment by hainguyenthe9** [comment]
t nghĩ phần này làm form phổ thông thôi nhỉ
đăng nhập. đăng ký bằng email, phải đăng nhập đúng tk mk mới cmt được ý kiến của mình dưới mỗi bài hát hoặc MV ca nhạc, ok k ?

**Comment by hthuy99** [comment]
mk phải tạo tài khoản zing khác chứ, như trang zing mp3 bây giờ ngta đăng kí bằng zalo còn mk
 bằng facebook or số đt

**Comment by hthuy99** [comment]
mn tìm hiểu xem cái plugin nào hỗ trợ cái nào thì mk cài cái ấy

**Comment by hainguyenthe9** [comment]
ừ, phải tạo tk zing riêng của web mình chứ..
đăng ký bằng email, fb or sdt cũng được... mình có thể thêm được mà

**Comment by hainguyenthe9** [comment]
Tạo thêm cái quên mật khẩu để đặt lại mk nếu người dùng quên mk nữa nhể

**Comment by hainguyenthe9** [comment]
giờ tìm hiểu plugin phù hợp là okeee rồi

**Comment by phuongnguyenthi251199** [comment]
https://vnfaster.com/huong-dan-tao-trang-dang-ky-cho-wordpress-khong-can-plugin.html

**Comment by phuongnguyenthi251199** [comment]
https://vnfaster.com/huong-dan-tao-trang-dang-nhap-wordpress-khong-can-plugin.html

**Comment by phuongnguyenthi251199** [comment]
mọi người tham khảo 2 link tạo trang đăng nhập / đăng kí này nhé

**Comment by phuongnguyenthi251199** [comment]
![image](https://user-images.githubusercontent.com/56269037/71400604-dbcfe080-2659-11ea-9faa-72e2f6572880.png)

**Comment by phuongnguyenthi251199** [comment]
đây là trang đăng nhập nha

**Comment by phuongnguyenthi251199** [comment]
đây là trang đăng kí nha

**Comment by phuongnguyenthi251199** [comment]
![image](https://user-images.githubusercontent.com/56269037/71400643-fdc96300-2659-11ea-948b-e979bb8d3053.png)

**Comment by phuongnguyenthi251199** [comment]
đây là trang đăng nhập

**Comment by hainguyenthe9** [comment]
oke

**Comment by hainguyenthe9** [comment]
để t đăng ký đăng nhập thử

**Comment by hainguyenthe9** [comment]
đang bị lỗi này

**Comment by hainguyenthe9** [comment]
![80511119_856638761406090_1896109365467807744_n](https://user-images.githubusercontent.com/51194378/71401709-3b7bbb00-265d-11ea-9f44-e41a4bf224b7.png)

**Comment by hainguyenthe9** [comment]
đăng xuất bị lỗi

**Comment by hainguyenthe9** [comment]
chắc chưa cài link cái href

**Comment by phuongnguyenthi251199** [comment]
nút thoát đã oke rồi nhé
