### ISSUE TITLE
Tải bài hát lên web

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#5]
i

**Comment by hainguyenthe9** [comment]
alo alo
nay làm cái này nhé

**Comment by hthuy99** [comment]
alo, chúng ta bắt đầu tải bài hát lên web đc rồi đó

**Comment by hainguyenthe9** [comment]
giờ cần đẩy dữ liệu bài hát từ db lên

**Comment by hainguyenthe9** [comment]
mọi người có phương án nào k?

**Comment by hainguyenthe9** [comment]
https://vi.blogpascher.com/wordpress-XNUMX/7-wordpress-plugins-free-to-th%C3%AAm-m%E1%BB%99t-ch%C6%A1i-tr%C3%AAn-audio-Blog-c%E1%BB%A7a-b%E1%BA%A1n

**Comment by hainguyenthe9** [comment]
https://taowebsite.com.vn/tao-am-thanh-cho-wordpress-tot-nhat/

**Comment by hainguyenthe9** [comment]
http://minhhn.com/wordpress/9-plugins-choi-nhac-tot-nhat-cho-wordpress/

**Comment by hainguyenthe9** [comment]
mọi người đọc thử mấy cái này xem, ổn k?

**Comment by hthuy99** [comment]
oke

**Comment by hthuy99** [comment]
tải bài hát lên web xong rồi nhé

**Comment by hainguyenthe9** [comment]
okeee, okeee..
thế là ổn rồi

**Comment by hainguyenthe9** [comment]
sang thảo luận chức năng tiếp theo đi

**Comment by hainguyenthe9** [comment]
alo alo, phần này ok chưa nhỉ
