### ISSUE TITLE
Tạo trang xếp hạng bài hát

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#7]

**Comment by hthuy99** [comment]
xếp hạng bài hát theo thứ tự mới ra hay theo lượt nghe v

**Comment by phuongnguyenthi251199** [comment]
theo lượt hot đó

**Comment by hthuy99** [comment]
https://thachpham.com/wordpress/wordpress-tutorials/chuc-nang-dem-luot-xem-va-top-bai-xem-nhieu.html

**Comment by hainguyenthe9** [comment]
oke, mọi người cứ tìm được link tham khảo thì post vào đây, ae xem rồi cùng làm cho nhanh

**Comment by hainguyenthe9** [comment]
mà cả xếp theo album nữa nhỉ

**Comment by hthuy99** [comment]
Hoặc sử dụng AJAX
https://thachpham.com/wordpress/wp-plugin/dem-luot-xem-bai-viet-khi-co-cache.html

**Comment by hthuy99** [comment]
bọn mk cứ code như này chắc oke

**Comment by hainguyenthe9** [comment]
ừ, ae đẩy nhanh lên thôi... 
mình còn chạy thử trước khi trả deadline :<

**Comment by phuongnguyenthi251199** [comment]
à cái tìm bài viết hay được mọi người truy cập thì t biết làm mà

**Comment by phuongnguyenthi251199** [comment]
có plugin đó

**Comment by hainguyenthe9** [comment]
thế hay

**Comment by hthuy99** [comment]
ừ thế cài plugin nhé cho nhanh

**Comment by hainguyenthe9** [comment]
thế oke rồi, cái nào dùng được plugin thì dùng, còn ko thì mình code

**Comment by hthuy99** [comment]
![screenshot-webdemo lionsoftwaresolutions com-2020 01 10-23_01_31](https://user-images.githubusercontent.com/56228860/72167199-42e0e980-33fd-11ea-842d-d43289e3ef7a.png)

**Comment by hainguyenthe9** [comment]
oke rồi đấy

**Comment by hthuy99** [comment]
![screenshot-webdemo lionsoftwaresolutions com-2020 01 10-23_04_52](https://user-images.githubusercontent.com/56228860/72167468-c13d8b80-33fd-11ea-9705-33f321fc47d8.png)

**Comment by hthuy99** [comment]
quên chưa up ảnh cái issues này :))

**Comment by hainguyenthe9** [comment]
ổn r đấy, vào BXH thì có BXH bài hát và gợi ý các bài hát khác cho người dùng

**Comment by hainguyenthe9** [comment]
![image](https://user-images.githubusercontent.com/51194378/72167642-1a0d2400-33fe-11ea-8298-b3cb8df0af0f.png)

**Comment by hainguyenthe9** [comment]
ở trang chủ cũng có luôn

**Comment by hainguyenthe9** [comment]
cái này là những bài hát hot hit gần đây

**Comment by hthuy99** [comment]
ngoài trang chủ là sương sương :)) oke r nhé
