### ISSUE TITLE
Chức năng đọc lời, nghe bài hát online

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#8]

**Comment by phuongnguyenthi251199** [comment]
chức năng đọc lời bài hát đơn giản là chỉ gõ lời bài hát tương ứng thôi nhỉ

**Comment by hthuy99** [comment]
ừ nhưng phải cho nó chạy thì làm thế nào nhỉ

**Comment by hainguyenthe9** [comment]
nếu mình tìm hiểu được cách thì như thế cũng hay

**Comment by hainguyenthe9** [comment]
còn không thì t nghĩ là khi người dùng nghe thì chỉ là nghe thôi, còn ở dưới sẽ có lời bài hát, tĩnh, k chạy

**Comment by hainguyenthe9** [comment]
giống web chiasenhac ấy

**Comment by hainguyenthe9** [comment]
alo alo

**Comment by hainguyenthe9** [comment]
![image](https://user-images.githubusercontent.com/51194378/72046498-1ccb2480-32eb-11ea-99d6-e4bcffb1a495.png)
phần đọc lời như thế này thôi nhỉ

**Comment by hainguyenthe9** [comment]
nghe nhạc thì oke rồi....
người dùng tìm kiếm hoặc dựa trên những bài hát gợi ý
click vào là nghe thôi

**Comment by phuongnguyenthi251199** [comment]
gợi ý cũng oke rồi

**Comment by phuongnguyenthi251199** [comment]
![image](https://user-images.githubusercontent.com/56269037/72046723-93682200-32eb-11ea-9236-45911b11b1a9.png)

**Comment by phuongnguyenthi251199** [comment]
gõ chưa ta là hiện ra 1 loạt kìa

**Comment by phuongnguyenthi251199** [comment]
các cậu ơi nhưng phải up thêm bài hát đi

**Comment by hainguyenthe9** [comment]
phải up thêm chứ, một số mục chủ đề còn ít bài quá kìa

**Comment by hainguyenthe9** [comment]
phần này cơ bản là xong rồi nhỉ
có lời bài hát
nghe bài hát cũng ok
còn gì nữa ko

**Comment by phuongnguyenthi251199** [comment]
oke h up thêm nhé

**Comment by hainguyenthe9** [comment]
ok ok, sang issues khác thôi

**Comment by phuongnguyenthi251199** [comment]
chỗ mục ca sĩ nổi tiếng nhé
