### ISSUE TITLE
Chức năng download bài hát cho người dùng

### ISSUE THREAD

**Issue by phuongnguyenthi251199** [phuongnguyenthi251199/SE03-Group-08#9]

**Comment by phuongnguyenthi251199** [comment]
có ai tìm hiểu về chức năng dowload bài hát xuống chưa

**Comment by hainguyenthe9** [comment]
https://vi.blogpascher.com/plugin-wordpress/10-plugins-cho-wordpress-h%E1%BB%A3p-m%E1%BB%99t-manager-%C4%91%E1%BB%83-t%E1%BA%A3i-xu%E1%BB%91ng

**Comment by hainguyenthe9** [comment]
trong đây có plugin này

**Comment by phuongnguyenthi251199** [comment]
oke cậu

**Comment by hainguyenthe9** [comment]
![79872698_1798050576995891_8113382952324300800_n](https://user-images.githubusercontent.com/51194378/71369680-185df680-25de-11ea-8502-63a0460deb43.png)

**Comment by hainguyenthe9** [comment]
alo alo, phần tải nhạc lên web và down nhạc về ok chưa?

**Comment by hthuy99** [comment]
oke  đấy

**Comment by hthuy99** [comment]
thế down về là về máy hay về tài khoản zing đấy b

**Comment by hainguyenthe9** [comment]
tải về máy tính

**Comment by hainguyenthe9** [comment]
http://webdemo.lionsoftwaresolutions.com/zingmp3/wordpress/4u-nhac-viet/

**Comment by phuongnguyenthi251199** [comment]
mọi người down thử đi thì biết haha

**Comment by hainguyenthe9** [comment]
mà mọi người thấy nên là đăng nhập vào rồi mới tải được hay là cứ thế là tải luôn nhỉ

**Comment by phuongnguyenthi251199** [comment]
nghe cũng có lý

**Comment by hthuy99** [comment]
thôi  mk cứ đăng nhập rồi mới tải cho đỡ fake :))

**Comment by hainguyenthe9** [comment]
oke

**Comment by hainguyenthe9** [comment]
nghe thì có thể nghe trực tuyển được, còn tải về thì phải đăng nhập
